name: Checkout-Code

on:
  workflow_call:
    inputs:
      service_name:
        description: 'Name of service/web app'
        required: false
        type: string   


env:
  SERVICE_NAME: ${{ inputs.service_name || github.event.repository.name  }}
  
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - 
       name: Checkout 
       uses: actions/checkout@v3
      -
       name : Check Direktory
       run: | 
         ls
         echo ${{ env.SERVICE_NAME }}