name: Docker-Build

on:
  workflow_call:
    inputs:
      service_name:
        description: 'Name of service/web app'
        required: false
        type: string   
    secrets:
      dh_username:
        required: true
      dh_token:
        required: true

env:
  SERVICE_NAME: ${{ inputs.service_name || github.event.repository.name  }}
  USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  MANGGILE: ${{ secrets.MANGGIL }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      -
       name : Check Direktory
       run: | 
         ls
         echo ${{ secrets.dh_username }}
         echo ${{ secrets.dh_token }}
         echo ${{ secrets.MANGGIL }}
         echo ${{ env.MANGGILE }}

      - 
        name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.dh_username }}
          password: ${{ secrets.dh_token }}
      - # stage build dan push docker 
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.docker_hub_username }}/case-study:${{ env.SERVICE_NAME }}-${{ github.run_number }}
